logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    com.sunglowsys: DEBUG

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/atithih_db
    username: postgres
    password: Password@123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
